name: who_boogles_it
description: "The game where you must guess the end of search requests"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  go_router: ^13.2.0
  easy_localization: ^3.0.3
  flutter_svg: ^2.0.9
  flutter_native_splash: ^2.3.10
  url_launcher: ^6.2.4
  flutter_bloc: ^8.1.4
  bloc: ^8.1.3
  isar: ^3.1.0  # web is not supported for now (4.0.0 with web support is prerelease)
  isar_flutter_libs: ^3.1.0
  multiavatar: ^0.1.5
  path_provider: ^2.1.2
  get_it: ^7.6.7
  equatable: ^2.0.5
  flutter_animate: ^4.5.0
  turn_page_transition: ^0.3.0
  animated_text_kit: ^4.2.2
  bubble: ^1.2.1
  smooth_counter: ^0.1.0
  jumping_dot: ^0.0.6
  wakelock: ^0.6.2
  lottie: ^3.1.0
  firebase_core: ^2.31.0
  firebase_analytics: ^10.10.5
  firebase_crashlytics: ^3.5.5
  firebase_performance: ^0.9.4+5

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  isar_generator: ^3.1.0
  build_runner: ^2.4.8
  mockito: ^5.4.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/jpg/
    - assets/images/svg/
    - assets/translations/
    - assets/anim/

  fonts:
    - family: MainFont
      fonts:
        - asset: assets/fonts/Tektur.ttf
