// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHxtoBBDv7Q4HWrBptSJK1IkxduXkiHDY',
    appId: '1:298087138346:android:562f39ab5ade695fe76f53',
    messagingSenderId: '298087138346',
    projectId: 'boogle-feud',
    storageBucket: 'boogle-feud.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK8TX2fTpja9OYC78kQuiTZ3Qd_Ezhs8s',
    appId: '1:298087138346:ios:eb78ed92bc9bee2be76f53',
    messagingSenderId: '298087138346',
    projectId: 'boogle-feud',
    storageBucket: 'boogle-feud.appspot.com',
    iosBundleId: 'com.ogurecapps.whoBooglesIt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWgDkry--s5da_E6dfdtdlRCRNNj8PvMU',
    appId: '1:298087138346:web:3f0bb200ffc4360de76f53',
    messagingSenderId: '298087138346',
    projectId: 'boogle-feud',
    authDomain: 'boogle-feud.firebaseapp.com',
    storageBucket: 'boogle-feud.appspot.com',
    measurementId: 'G-K7Z1K7J026',
  );

}